### PR TITLE
feedback bugfix, sorting of unfinished list

### PR DESCRIPTION
**Pull request by jendamozna**
- feedback fixed for unfinished items
- sorting of unfinished broadcasts added (the nearest one stored in Unfinished#0)

### CODE REVIEW

**Comment by josephdadams** [comment]
@jendamozna please version bump `package.json`

**Comment by whizkidTRW** [comment]
@jendamozna Any progress on this latest update? I'm eagerly awaiting this progress!

**Comment by jendamozna** [comment]
> @jendamozna Any progress on this latest update? I'm eagerly awaiting this progress!

Waiting for merge.

**Comment by josephdadams** [comment]
@jendamozna what's with the build errors?

**Pull request merged**
